# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b5ad8ba81313338cdab6a9956b51a659c8e150d3fe58d40c2980edb2384316f9c33de541ababbbde6f97101ecfd91ea0fd41a1c4787fe0b5d1de910b0f6504ad

test:
  secret_key_base: 4e014f362372a1674dbfe062c529dcccbb7a6de8271b76c6c712df74fb74e7632f24f195f76f984b4443a51eeb91f4258f6c4009d0ee17cb2948f49bf4a8624d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
